version: '3'

services:
  ssh-server:
    build: .
    image: docker-ubuntu-ssh-server
    container_name: docker-ubuntu-ssh-server
    networks:
      web-demo:
        ipv4_address: 10.10.10.2
    ports:
      - "8001:22/udp"
      - "8002:22/tcp"
    restart: always
  http2-h2c:
    build: /http2-h2c/.
    image: http2-h2c
    container_name: http2-h2c
    volumes:
      - ./http2-h2c/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8003:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.3
  http2-h2:
    build: /http2-h2/.
    image: http2-h2
    container_name: http2-h2
    volumes:
      - ./http2-h2/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8004:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.4
  http1.1:
    build: /http1.1/.
    image: http1.1
    container_name: http1.1
    volumes:
      - ./http1.1/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8005:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.5
networks:
  web-demo:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/16
          gateway: 10.10.10.1