version: '3'

services:
  ssh-server:
    build: .
    image: docker-ubuntu-ssh-server
    container_name: docker-ubuntu-ssh-server
    networks:
      web-demo:
        ipv4_address: 10.10.10.2
    ports:
      - "8001:22/udp"
      - "8002:22/tcp"
    restart: always
  http2-h2c:
    build: /http2-h2c/.
    image: http2-h2c
    container_name: http2-h2c
    volumes:
      - ./http2-h2c/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8003:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.3
  http2-h2:
    build: /http2-h2/.
    image: http2-h2
    container_name: http2-h2
    volumes:
      - ./http2-h2/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8004:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.4
  http1.1:
    build: /http1.1/.
    image: http1.1
    container_name: http1.1
    volumes:
      - ./http1.1/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8005:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.5
  http_ssl_not_http2:
    build: /http_ssl_not_http2/.
    image: http_ssl_not_http2
    container_name: http_ssl_not_http2
    volumes:
      - ./http_ssl_not_http2/build/app.jar:/data/projects/app/app.jar
    ports:
      - 8006:8080
    restart: always
    networks:
      web-demo:
        ipv4_address: 10.10.10.6
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    networks:
      web-demo:
        ipv4_address: 10.10.10.7
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 8007:3000 #optional
    restart: unless-stopped
    command:
      - apk add curl
networks:
  web-demo:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/16
          gateway: 10.10.10.1