FROM adoptopenjdk/openjdk8:ubi

WORKDIR /

# tạo folder
RUN mkdir -p /data/projects/app
RUN mkdir -p /data/projects/app/file

# coppy file tại thư mục chạy cậu lệnh, đến thư mục với tên file trong image
# COPY dist/app.jar /data/projects/app/app.jar
WORKDIR /data/projects/app
# start
CMD ["java","-jar", "app.jar"]
